<a href="https://colab.research.google.com/github/DavidSenseman/BIO1173/blob/main/Class_05_1_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---------------------------
**COPYRIGHT NOTICE:** This Jupyterlab Notebook is a Derivative work of [Jeff Heaton](https://github.com/jeffheaton) licensed under the Apache License, Version 2.0 (the "License"); You may not use this file except in compliance with the License. You may obtain a copy of the License at

> [http://www.apache.org/licenses/LICENSE-2.0](http://www.apache.org/licenses/LICENSE-2.0)

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

------------------------

# **BIO 1173: Intro Computational Biology**

##### **Module 5: Natural Language Processing**

* Instructor: [David Senseman](mailto:David.Senseman@utsa.edu), [Department of Biology, Health and the Environment](https://sciences.utsa.edu/bhe/), [UTSA](https://www.utsa.edu/)

### Module 4 Material

* **Part 5.1: Introduction to Hugging Face**
* Part 5.2: Hugging Face Tokenizers
* Part 5.3: Hugging Face Datasets
* Part 5.4: Training Hugging Face models

## Google CoLab Instructions

You MUST run the following code cell to get credit for this class lesson. By running this code cell, you will map your GDrive to /content/drive and print out your Google GMAIL address. Your Instructor will use your GMAIL address to verify the author of this class lesson.

In [1]:
# You must run this cell first
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    from google.colab import auth
    auth.authenticate_user()
    Colab = True
    print("Note: Using Google CoLab")
    import requests
    gcloud_token = !gcloud auth print-access-token
    gcloud_tokeninfo = requests.get('https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=' + gcloud_token[0]).json()
    print(gcloud_tokeninfo['email'])
except:
    print("**WARNING**: Your GMAIL address was **not** printed in the output below.")
    print("**WARNING**: You will NOT receive credit for this lesson.")
    Colab = False

Mounted at /content/drive
Note: Using Google CoLab
david.senseman@gmail.com


You should see the following output except your GMAIL address should appear on the last line.

![__](https://biologicslab.co/BIO1173/images/class_04/class_04_1_image01B.png)

If your GMAIL address does not appear your lesson will **not** be graded.

### Runtime type for Class_05_1

For this lesson GPU hardware accelerations is **optional**. Your lesson will defintely run faster with GPU acceleration, but the lesson can be completed only a "cpu" runtime. If you decide to use GPU acceleration, the **T4 GPU** would be fine.

### **YouTube Introduction to Hugging Face**

Run the next cell to see short introduction to Hugging Face. This is a suggested, but optional, part of the lesson.

In [2]:
from IPython.display import HTML
video_id = "GLO5FZzfrS0"

HTML(f"""
<iframe width="560" height="315"
  src="https://www.youtube.com/embed/{video_id}"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
  allowfullscreen
  referrerpolicy="strict-origin-when-cross-origin"> </iframe>
""")

# **Introduction to Hugging Face**

**Hugging Face** is a company renowned for its pioneering work in the realm of Natural Language Processing (NLP). Established in 2016, Hugging Face has become synonymous with making cutting-edge NLP technologies more accessible to developers, researchers, and organizations. The company's commitment to open-source development has fostered a vibrant community, which plays a pivotal role in the rapid advancements of the field.

Central to Hugging Face's acclaim is the Transformers library. This Python library provides an extensive collection of pre-trained models that span a wide range of NLP tasks, from text classification and tokenization to language modeling and translation. Some of the most groundbreaking models like BERT, GPT-2, T5, and RoBERTa can be effortlessly accessed and deployed through this library.

A notable feature of the Transformers library is its user-friendly API. With just a few lines of code, one can:

* Load a pre-trained model.
* Tokenize input text.
* Obtain model predictions or embeddings.
* Fine-tune the model on a specific task.

This ease of use, combined with comprehensive documentation and tutorials, makes it an invaluable tool for both NLP newcomers and seasoned professionals.

Another significant contribution from Hugging Face is the Model Hub, a platform where researchers and developers can share, discover, and use NLP models. The hub promotes collaboration, ensuring that state-of-the-art models are easily available to the wider community. It's not uncommon to see models from recent research papers promptly available on the hub, ready for real-world applications.

Tokenization, the process of converting text into tokens, is a fundamental step in NLP. Recognizing its importance, Hugging Face introduced the Tokenizers library, which provides a fast and efficient way to tokenize massive datasets without compromising on accuracy. Its compatibility with the Transformers library ensures seamless integration between tokenization and modeling.

Democratization of NLP: By making advanced models and tools accessible, Hugging Face has democratized NLP, enabling even small teams or individual developers to harness the power of state-of-the-art models.

Rapid Prototyping: The ease with which one can deploy models means that ideas can be tested and iterated upon swiftly, accelerating the pace of NLP advancements.

Community and Collaboration: The open-source ethos of Hugging Face has cultivated a community that collaborates, contributes, and ensures that the field remains vibrant and progressive.

In the ever-evolving landscape of NLP, Hugging Face stands out as a beacon of innovation, accessibility, and collaboration. Whether you are a researcher pushing the boundaries of what's possible, a developer aiming to integrate NLP into an application, or an enthusiast eager to learn, Hugging Face provides the tools and resources to realize those ambitions. As we delve deeper into this book, we will frequently use the Hugging Face platform to illustrate concepts, implement solutions, and explore the vast possibilities of NLP.



### **Using Python with Hugging Face**

Transformers have become a mainstay of natural language processing. This module will examine the [Hugging Face](https://huggingface.co/) Python library for natural language processing, bringing together pretrained transformers, data sets, tokenizers, and other elements. Through the Hugging Face API, you can quickly begin using sentiment analysis, entity recognition, language translation, summarization, and text generation.

Colab does not install Hugging face by default. Whether installing Hugging Face directly into a local computer or utilizing it through Colab, the following commands will install the library.

Normally, when you use `pip` to install a package, a lot of information is printed out to show what subpackages were installed. We have prevented this by
adding the text `> /dev/` after the `!pip install <package>`. Technically, this code `redirects` the standard output (in this case your Colab notebook) to a device called `null`. `/dev/null` is a special file that discards all data written to it. It is often used as a "black hole" for unwanted output or error messages, such as the output of commands that are meant to be silent or hidden.


### Log into Hugging Face

Run the next code cell to log into your Hugging Face account using your `HF_Token` stored in your Colab Secrets. You may have to grant access to your Colab Secrets.

In [3]:
# Log into Hugging Face.

from google.colab import userdata
from huggingface_hub import login

# Get the token from Colab Secrets and log in
try:
    hf_token = userdata.get('HF_Token')
    login(token=hf_token)
    print("Successfully logged into Hugging Face!")
except Exception as e:
    print(f"Error logging into Hugging Face: {e}")


Successfully logged into Hugging Face!


### Install Hugging Face Libraries

Run the next code cell to install the Hugging Face libraries needed for this lesson.

If your `HF_Token` is correctly stored in your Colab Secrets, you should see the following output:

```text
Successfully logged into Hugging Face!
```

Information how to obtain your `HF_Token` and store it in your Colab Secrets has already been provided to you. If you are haven't trouble getting it to work, please see the course Instructor or a TA.  

In [4]:
# Install Hugging Face libraries

!pip install -q transformers
!pip install -q transformers[sentencepiece]

If the code is correct you should _not_ see any output.

Now that we have Hugging Face installed, the following sections will demonstrate how to apply Hugging Face to a variety of everyday tasks. After this introduction, the remainder of this module will take a deeper look at several specific NLP tasks applied to Hugging Face.

# **NLP Sentiment Analysis**

**Sentiment analysis** is a subfield of natural language processing (NLP) that focuses on identifying and categorizing the emotional tone or sentiment of a piece of text, such as a review, a social media post, or an article. The task of sentiment analysis involves analyzing the words and phrases in a given text to determine whether they are positive, negative, or neutral in nature, and assigning a numerical score or label to the overall sentiment of the text.

Sentiment analysis can be applied to various domains such as social media monitoring, customer feedback analysis, product review analysis, and advertising campaign evaluation. It can help organizations to identify trends and patterns in customer opinion, detect fake reviews, and optimize their marketing strategies by understanding the emotions of their target audience.

### What is sentiment analysis?

Sentiment analysis is a subfield of natural language processing (NLP) that focuses on identifying and categorizing the emotional tone or sentiment of a piece of text, such as a review, a social media post, or an article. The task of sentiment analysis involves analyzing the words and phrases in a given text to determine whether they are positive, negative, or neutral in nature, and assigning a numerical score or label to the overall sentiment of the text.

Sentiment analysis can be applied to various domains such as social media monitoring, customer feedback analysis, product review analysis, and advertising campaign evaluation. It can help organizations to identify trends and patterns in customer opinion, detect fake reviews, and optimize their marketing strategies by understanding the emotions of their target audience.

The process of sentiment analysis typically involves several steps, including:

1. Text Preprocessing: This step involves cleaning and normalizing the text data to prepare it for analysis. This may include removing stop words, punctuation, and converting all text to lowercase.
2. Tokenization: This step involves breaking down the text into smaller units called tokens, which can be individual words or phrases.
3. Sentiment Detection: This step involves analyzing the sentiment of each token in the text using techniques such as machine learning, deep learning, or rule-based approaches.
4. Aggregation: This step involves combining the sentiment scores of all tokens to obtain the overall sentiment score of the text.

Sentiment analysis can be performed using various techniques such as:

1. **Rule-Based Approach:** This approach involves defining a set of rules to classify words or phrases as positive, negative, or neutral based on their meanings and context.
2. **Machine Learning:** This approach involves training a machine learning model on a dataset of labeled text to learn the patterns and relationships between words and sentiment.
3. **Deep Learning:** This approach involves using deep neural networks to analyze the complex patterns in text data and learn the relationships between words, phrases, and sentiment.

Sentiment analysis uses natural language processing, text analysis, computational linguistics, and biometrics to identify the tone of written text. Passages of written text can be into simple binary states of positive or negative tone. More advanced sentiment analysis might classify text into additional categories: sadness, joy, love, anger, fear, or surprise.


### Example 1 - Step 1: Load Text for Sentiment Analyis

To demonstrate sentiment analysis, we begin by loading Shakespeare's 18th sonnet:

> Shall I compare thee to a summer's day?  
> Thou art more lovely and more temperate:  
> Rough winds do shake the darling buds of May,  
> And summer's lease hath all too short a date:  
> Sometime too hot the eye of heaven shines,  
> And often is his gold complexion dimm'd;  
> And every fair from fair sometimes declines,  
> By chance or nature's changing course untrimm'd;  
> But thy eternal summer shall not fade  
> Nor lose possession of that fair thou owest;  
> Nor shall Death brag thou wander'st in his shade,  
> When in eternal lines to time thou growest.

What do you think Shakespear's sentiment was when he wrote this sonnet? In particular, is Shakespear being **positive** or **negative**?

Let's find out using **sentiment analysis**.

In Step 1 we read the text file "sonnet_18.txt" from the course file server using the `urlopen()` command. The text is stored in a variable called `eg_text_1` ("Example text 1").

In [5]:
# Example 1 - Step 1: Load text

from urllib.request import urlopen

# Read sample text, a poem
URL = "https://biologicslab.co/BIO1173/data/sonnet_18.txt"
f = urlopen(URL)
eg_text_1 = f.read().decode("utf-8")

# Print out text
print(eg_text_1)

Shall I compare thee to a summer's day?
Thou art more lovely and more temperate:
Rough winds do shake the darling buds of May,
And summer's lease hath all too short a date:
Sometime too hot the eye of heaven shines,
And often is his gold complexion dimm'd;
And every fair from fair sometimes declines,
By chance or nature's changing course untrimm'd;
But thy eternal summer shall not fade
Nor lose possession of that fair thou owest;
Nor shall Death brag thou wander'st in his shade,
When in eternal lines to time thou growest.


If the code is correct your should see the following output

```text
Shall I compare thee to a summer's day?
Thou art more lovely and more temperate:
Rough winds do shake the darling buds of May,
And summer's lease hath all too short a date:
Sometime too hot the eye of heaven shines,
And often is his gold complexion dimm'd;
And every fair from fair sometimes declines,
By chance or nature's changing course untrimm'd;
But thy eternal summer shall not fade
Nor lose possession of that fair thou owest;
Nor shall Death brag thou wander'st in his shade,
When in eternal lines to time thou growest.
```

In the next step, we will use this poem by William Shakespear for our sentiment analysis.

Usually, you have to preprocess text into embeddings or other vector forms before presentation to a neural network. Hugging Face provides a pipeline that simplifies this process greatly. The pipeline allows you to pass regular Python strings to the transformers and return standard Python values.

We begin by loading a text-classification model. We can specify which model to use, by passing the model parameter, such as:

```
pipe = pipeline(model="roberta-large-mnli")
```

**RoBERTa-large-MNLI** is a fine-tuned version of the RoBERTa large model, which is a transformer-based language model developed by Facebook AI. RoBERTa itself is an optimized version of BERT (Bidirectional Encoder Representations from Transformers) and is trained on a large corpus of English text using a masked language modeling (MLM) objective.

The code in Example 1 - Step 2 loads a model pipeline and a model for sentiment analysis.



### Example 1 - Step 2: Load Model Pipeline

This code in the cell below uses the `transformers library` to create a pipeline for natural language inference (NLI) tasks. The pipeline function takes a model name as an argument, which in this case is "roberta-large-mnli". This specific model is a variant of the `RoBERTa model` that has been pre-trained on a large dataset of text and can perform NLI tasks such as question answering or natural language inference.

The pipeline function returns an instance of a Pipeline class from the transformers library, which is a high-level API for interacting with NLP models. The returned pipeline object has methods for various NLI tasks such as question answering, natural language inference, and text classification.

In this specific case, the code is creating a pipeline for natural language inference tasks using the "roberta-large-mnli" model. This means that it can be used to perform NLI tasks such as determining the meaning of a sentence or question given some context. The Pipeline object returned by the pipeline function will have methods for performing these tasks, such as predict and score, which can be used to make predictions on new input data and evaluate the performance of the model.

In [6]:
# Example 1 - Step 2: Load model pipeline

import pandas as pd
from transformers import pipeline, logging

# Suppress the warning (optional)
logging.set_verbosity_error()

# Specify the model for the pipeline
model_name = "roberta-large-mnli"

# Create classification pipeline
classifier = pipeline("text-classification", model=model_name)

# Verify the pipeline
print(classifier)


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/688 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.43G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

If the code is correct you should see something similar to the following output:

```text
<transformers.pipelines.text_classification.TextClassificationPipeline object at 0x798446116fc0>
```

We can now display the sentiment analysis results as a `Pandas` DataFrame.


### Example 1 - Step 3: Run Sentiment Analysis on Text

We can now display the sentiment analysis results with a Pandas dataframe.

In [7]:
# Example 1 - Step 3: Run sentiment analysis on text

# Create variable to hold sentiment analysis
sentiment_outputs = classifier(eg_text_1)

# Display output in a Pandas DataFrame
pd.DataFrame(sentiment_outputs)


label     score
0  NEUTRAL  0.679496

If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image03F.png)

As you can see, our sentiment analysis considered the tone of Sonnet 18 as being `NEUTRAL` with a `score` of 0.68.

Shakespeare's Sonnet 18 is generally considered to have positive and admiring sentiment. The sonnet praises the subject, comparing them to a summer's day and highlighting their eternal beauty and the impermanence of natural beauty.

So why did we get only a `NEUTRAL` rating?

Sentiment analysis models like **`RoBERTa-large-MNLI`** work by analyzing the text and classifying it based on the presence of positive, negative, or neutral sentiments. Shakespeare's `Sonnet 18` ("Shall I compare thee to a summer's day?") is a complex and nuanced piece of literature, which can make it challenging for an AI model to accurately classify its sentiment.

Several factors could have contributed to the neutral sentiment classification:

1. **Language and Style:** Shakespeare's language and poetic style are intricate, with a mix of positive imagery and more neutral or descriptive language. This complexity might have led the model to classify the overall sentiment as neutral.

2. **Ambiguity:** The sonnet contains elements of praise and admiration, but it also discusses the transience of beauty and the passage of time, which might have contributed to a more balanced or neutral sentiment score.

3. **Contextual Understanding:** AI models might struggle with understanding the full context and emotional depth of the text. They might miss subtleties that human readers would easily pick up on.

The `0.6795 score` indicates that the model is fairly confident in its neutral classification, but it doesn't mean the text lacks positive sentiment. It just means that the model detected a more balanced mix of sentiments overall.

### **Exercise 1 - Step 1: Load Text for Sentiment Analyis**

For **Exercise 1**, use Shakespear's Sonnet 66.

**Sonnet 66**

> Tired with all these, for restful death I cry:  
> As, to behold desert a beggar born,  
> And needy nothing trimmed in jollity,  
> And purest faith unhappily forsworn,  
> And gilded honor shamefully misplaced,  
> And maiden virtue rudely strumpeted,  
> And right perfection wrongfully disgraced,  
> And strength by limping sway disablèd,  
> And art made tongue-tied by authority,  
> And folly, doctor-like, controlling skill,   
> And simple truth miscalled simplicity,  
> And captive good attending captain ill.  
>   Tired with all these, from these would I be gone,  
>   Save that, to die, I leave my love alone.  


Here is the `URL` to download this poem:

```text
URL = "https://biologicslab.co/BIO1173/data/sonnet_66.txt"
```

Call your text **`ex_text_1`** and print out `ex_test_1` at the end of the code cell.


In [8]:
# Insert your code for Exercise 1 - Step 1 here

from urllib.request import urlopen

# Read sample text, a poem
URL = "https://biologicslab.co/BIO1173/data/sonnet_66.txt"
f = urlopen(URL)
ex_text_1 = f.read().decode("utf-8")

# Print out text
print(ex_text_1)

Tired with all these, for restful death I cry:
As, to behold desert a beggar born,
And needy nothing trimmed in jollity,
And purest faith unhappily forsworn,
And gilded honor shamefully misplaced,
And maiden virtue rudely strumpeted,
And right perfection wrongfully disgraced,
And strength by limping sway disablèd,
And art made tongue-tied by authority,
And folly, doctor-like, controlling skill,
And simple truth miscalled simplicity,
And captive good attending captain ill.
 Tired with all these, from these would I be gone,
 Save that, to die, I leave my love alone.


If the code is correct your should see the following output

```text
Tired with all these, for restful death I cry:
As, to behold desert a beggar born,
And needy nothing trimmed in jollity,
And purest faith unhappily forsworn,
And gilded honor shamefully misplaced,
And maiden virtue rudely strumpeted,
And right perfection wrongfully disgraced,
And strength by limping sway disablèd,
And art made tongue-tied by authority,
And folly, doctor-like, controlling skill,
And simple truth miscalled simplicity,
And captive good attending captain ill.
 Tired with all these, from these would I be gone,
 Save that, to die, I leave my love alone.
 ```

### **Exercise 1 - Step 2: Load Model Pipeline**

In the cell below create the pipeline for your sentiment analysis. You can reuse the code in Example 1 - Step 2 with the following modification. Instead of using the `"roberta-large-mnli"` model, change your model to the following:

```text
"distilbert-base-uncased-finetuned-sst-2-english"
```

The **`distilbert-base-uncased-finetuned-sst-2-english`** model is a lightweight, 66 M‑parameter transformer that was distilled from BERT‑base and fine‑tuned on the Stanford Sentiment Treebank (SST‑2) for binary sentiment classification. Using an uncased WordPiece tokenizer and a 512‑token limit, the model maps input text to a pair of logits (positive/negative) through a simple linear head on the [CLS] token; applying a softmax gives the sentiment probability. It achieves roughly 93 % accuracy on SST‑2, matching full BERT‑base while running about twice as fast and using half the memory, making it ideal for quick sentiment inference on English text in production settings.

In [9]:
# Insert your code for Exercise 1 - Step 2 here

import pandas as pd
from transformers import pipeline, logging

# Suppress the warning (optional)
logging.set_verbosity_error()

# Specify the model for the pipeline
model_name = "distilbert-base-uncased-finetuned-sst-2-english"

# Create classification pipeline
classifier = pipeline("text-classification", model=model_name)

# Verify the pipeline
print(classifier)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image01F.png)

### **Exercise 1 - Step 3: Run Sentiment Analysis on Text**

In the cell below write the code to run and display the sentiment analysis on your **`ex_text_1`**.

In [10]:
# Insert your code for Exercise 1 - Step 3 here

# Create variable to hold sentiment analysis
sentiment_outputs = classifier(ex_text_1)

# Display output in a Pandas DataFrame
pd.DataFrame(sentiment_outputs)


label     score
0  NEGATIVE  0.995461

If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image04G.png)

Shakespeare's Sonnet 66 indeed carries a much darker tone compared to Sonnet 18. Here are a few reasons why the sentiment analysis model might have given it a strong negative sentiment classification:

1. **Tone and Themes:** Sonnet 66 delves into themes of despair, disillusionment, and a profound sense of weariness with the world's injustices. The recurring motifs of frustration and longing for rest likely contributed significantly to the negative sentiment score.

2. **Language and Imagery:** The sonnet is filled with negative imagery and phrases expressing dissatisfaction and lamentation. Such language naturally skews towards a negative sentiment classification by the model.

3. **Emotional Weight:** The emotional heaviness and the poet’s voice reflecting societal corruption and personal sorrow might resonate strongly with the AI model’s parameters for negative sentiment.

The score of `0.995` indicates an almost complete certainty by the model that the sentiment is negative, which aligns well with the sonnet’s content and tone.

## **NLP Entity Tagging**

**Entity tagging**, also known as named entity recognition (NER), is a process in natural language processing (NLP) where entities such as names of people, organizations, locations, dates, and other specific items are identified and classified within a text. Here’s how it works:

1. **Identification:** The model scans the text to find mentions of entities. For example, in the sentence "Microsoft was founded by Bill Gates in 1975," the entities are "Microsoft," "Bill Gates," and "1975."

2. **Classification:** Once identified, the entities are classified into predefined categories, such as:

- **Person:** Names of individuals (e.g., "Bill Gates")

- **Organization:** Names of companies, institutions, etc. (e.g., "Microsoft")

- **Location:** Names of places (e.g., "Seattle")

- **Date/Time:** Specific dates or times (e.g., "1975")

- **Others:** Such as events, quantities, monetary values, etc.

Entity tagging is widely used in various applications like information extraction, search engines, and enhancing the accuracy of machine translation. It helps in structuring unstructured text data, making it easier to analyze and extract meaningful insights.

Entity tagging is the process that takes source text and finds parts of that text that represent entities, such as one of the following:

* Location (LOC)
* Organizations (ORG)
* Person (PER)
* Miscellaneous (MISC)

The code in Example 2 requests a "named entity recognizer" (ner) and processes the specified text.

### Example 2 - Step 1: Entity Tagging

The code in the cell below creates a variable, `eg_text_2` with the name of a famous molecular biologist, `James Watson` in the United States.

In [11]:
# Example 2 - Step 1: Entity tagging

# Specify text
eg_text_2 = "James Watson was a molecular biologist who lived in the United States."

# Create one pipeline instance for each task
classifier = pipeline("text-classification", model="roberta-large-mnli")
ner_tagger   = pipeline("ner", model="dslim/bert-base-NER", aggregation_strategy="simple")

# Classification
print(classifier(eg_text_2))     # MNLI style entailment / contradiction / neutral

# NER
print(ner_tagger(eg_text_2))


config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

[{'label': 'NEUTRAL', 'score': 0.6941731572151184}]
[{'entity_group': 'PER', 'score': np.float32(0.99971426), 'word': 'James Watson', 'start': 0, 'end': 12}, {'entity_group': 'LOC', 'score': np.float32(0.99945664), 'word': 'United States', 'start': 56, 'end': 69}]


If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image02G.png)

### Example 2 - Step 2: Review the Results

The code in the next cell let us view the results stored in the `Pandas` DataFrame.  As you can see in the output, the person (`PER`) is `James Watson` and the location (`LOC`) is the `United States`.

In [12]:
# Example 2 - Step 2: Review results

# Define outputs
outputs = ner_tagger(eg_text_2)

# Display Output DataFrame
pd.DataFrame(outputs)


entity_group     score           word  start  end
0          PER  0.999714   James Watson      0   12
1          LOC  0.999457  United States     56   69

If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image03G.png)

Your entity tagging pipeline has successfully identified and classified "James Watson" as a person and "United States" as a location with very high confidence.

### **Exercise 2 - Step 1: Entity Tagging**

In the cell below create a variable, `ex_text_2` with the name of another famous molecular biologist, `Francis Crick` in the `United Kingdom`.

In [13]:
# Insert your code for Exercise 2 - Step 1 here

# Specify text
ex_text_2 = "Francis Crick was a molecular biologist who lived in the United Kingdom."

# Create one pipeline instance for each task
classifier = pipeline("text-classification", model="roberta-large-mnli")
ner_tagger   = pipeline("ner", model="dslim/bert-base-NER", aggregation_strategy="simple")

# Classification
print(classifier(ex_text_2))     # MNLI style entailment / contradiction / neutral

# NER
print(ner_tagger(ex_text_2))

[{'label': 'NEUTRAL', 'score': 0.6580846905708313}]
[{'entity_group': 'PER', 'score': np.float32(0.99934936), 'word': 'Francis Crick', 'start': 0, 'end': 13}, {'entity_group': 'LOC', 'score': np.float32(0.9994767), 'word': 'United Kingdom', 'start': 57, 'end': 71}]


If the code is correct you should see something similar to the following output:

```text
[{'label': 'NEUTRAL', 'score': 0.6580846905708313}]
[{'entity_group': 'PER', 'score': np.float32(0.99934936), 'word': 'Francis Crick', 'start': 0, 'end': 13}, {'entity_group': 'LOC', 'score': np.float32(0.9994767), 'word': 'United Kingdom', 'start': 57, 'end': 71}]
```

### **Exercise 2 - Step 2: Review the Results**

In the cell below write the code to define and review the results of your **`ex_text_2`**.

In [14]:
# Insert your code for Exercise 2 - Step 2: here

# Define outputs
outputs = ner_tagger(ex_text_2)

# Display Output DataFrame
pd.DataFrame(outputs)


entity_group     score            word  start  end
0          PER  0.999349   Francis Crick      0   13
1          LOC  0.999477  United Kingdom     57   71

If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image05G.png)

Your entity tagging pipeline has successfully identified and classified "Francis Crick" as a person and "United Kingdom" as a location with very high confidence.

## **NLP Question Answering**

**Question Answering (QA)** is a powerful NLP task that involves providing precise answers to questions based on a given reference text. This capability is incredibly useful in various applications, such as information retrieval, and educational tools.

Here's a quick rundown of how QA works:

1. **Reference Text:** A passage or document from which the answer can be extracted.

2. **Question:** A specific query related to the reference text.

3. **Answer Extraction:** The NLP model processes the reference text to find the exact segment that answers the question.

#### **Use Cases for a Computational Biologist**

For a computational biologist, “QA analysis” usually refers to **question‑answering** systems that can interrogate large biological data sets, literature corpora, and simulation outputs.  Below are practical ways the technology can be applied in a research or industrial setting.

| Use Case | What the QA system does | Typical inputs | Typical outputs | Why it matters |
|----------|------------------------|----------------|-----------------|----------------|
| **Literature mining & summarization** | Reads PubMed, bioRxiv, and review articles to answer specific biological questions (e.g., “Which genes are co‑expressed with *TP53* in breast cancer?”). | Natural‑language query + optional PMID set | Short answer, evidence sentences, citation list | Speeds up hypothesis generation and keeps investigators up‑to‑date. |
| **Protocol & pipeline verification** | Checks whether computational workflows (e.g., variant‑calling pipelines) meet best‑practice standards or regulatory requirements. | Pipeline description, code, test logs | Pass/fail verdict, compliance report | Helps avoid costly downstream errors and accelerates reproducibility. |
| **Clinical data interrogation** | Answers clinical questions from electronic health records or multi‑omics datasets (“What is the probability that a patient with X mutation will respond to drug Y?”). | Structured patient data, genomic profiles | Risk score, confidence interval, relevant literature | Supports precision‑medicine decisions. |
| **Drug‑target & repurposing discovery** | Queries databases (DrugBank, ChEMBL) to find potential new targets or off‑target effects. | Chemical structure or name, target protein | List of candidate targets, predicted affinity scores | Narrows experimental screening lists. |
| **Ontology & annotation assistance** | Maps free‑text notes or sequence motifs to controlled vocabularies (GO, MeSH). | Raw text, protein FASTA | Curated annotations, suggested terms | Improves data standardization for downstream analysis. |
| **Model validation & debugging** | Interrogates machine‑learning models to expose decision pathways (“Why did the model predict a splice‑site mutation is benign?”). | Model, input features, intermediate activations | Explanatory text, feature importance, counter‑factuals | Enhances trust and aids model refinement. |
| **Educational & training support** | Answers students’ queries during bioinformatics courses (e.g., “Explain the difference between UTRs and introns”). | Student question | Concise, citation‑backed answer | Lowers the learning curve for new trainees. |

#### **How it typically works**
1. **Indexing** – Textual resources (papers, databases, logs) are pre‑processed and stored in a vector‑search index.  
2. **Query processing** – The user’s natural‑language question is encoded into a vector and matched against the index.  
3. **Answer generation** – The system extracts the most relevant passages, optionally runs a language‑model head to paraphrase or synthesize an answer, and tags the answer with evidence citations.  
4. **Human‑in‑the‑loop** – Domain experts review the answer; feedback is fed back into the model for continual improvement.

By integrating QA analysis into the computational biology workflow, researchers can dramatically reduce the time spent on literature reviews, data curation, and pipeline troubleshooting, allowing more focus on discovery and hypothesis testing.


### Build QA Pipeline

The code in the cell below builds a **Questioning Answering (QA)** pipeline.

In [15]:
# Build pipeline

from transformers import pipeline

# Build the question‑answering pipeline (GPU is auto‑selected if available)
qa_pipe = pipeline(
    task="question-answering",
    model="distilbert-base-uncased-distilled-squad",  # any QA‑ready model works
)

print(" QA pipeline is ready!")


config.json:   0%|          | 0.00/451 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

 QA pipeline is ready!


If the code is correct you should see the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image06G.png)

### Example 3: Generate QA Result

The code in the cell below uses our `QA Pipeline` to ask the question

```text
"what shall fade"
```
The `context` of this question is Shakespear's `Sonnet 18` stored in `eg_text_1` that we created above in `Example 1`.

In [16]:
# Example 3: Generate QA result

# Define the context and the question you want answered
context = eg_text_1  # Sonnet 18 from Example 1

# Define the question
question = "what shall fade"

# Run the QA model
result = qa_pipe(question=question, context=context)

# Pretty‑print the answer
print(f"Question: {question}")
print(f"Answer  : {result['answer']}")
print(f"Score   : {result['score']:.4f}")
print(f"Start   : {result['start']}  End: {result['end']}")


Question: what shall fade
Answer  : eternal summer
Score   : 0.3792
Start   : 367  End: 381


If the code is correct you should see the following output:
```text
Question: what shall fade
Answer  : eternal summer
Score   : 0.3792
Start   : 367  End: 381
```

With a `Score = 0.38`, Hugging Face `distilbert-base-uncased-distilled-squad` model is not especially confident that `external summer` is the correct answer to our question `what will fade` in Shakespear's Sonnet 18.

### **Exercise 3: Generate QA Result**

The following is a famous quotation by the molecular geneticist James Watson as the forward to _Discovering the Brain_ by Sandra Ackerman.

```type
"The brain is the last and grandest biological frontier,"
"the most complex thing we have yet discovered in our universe."
"It contains hundreds of billions of cells interlinked through "
"trillions of connections. The brain boggles the mind."
```

For **Exercise 3** you are to use Watson's quote as the `context`. The easiest way to do this is to `copy-and-paste` the quotation into space between the two parantheses as follows:

```text
Watson_quotation = (
"The brain is the last and grandest biological frontier,"
"the most complex thing we have yet discovered in our universe."
"It contains hundreds of billions of cells interlinked through "
"trillions of connections. The brain boggles the mind."
)  
```
You will need to assign the `context` to your `Watson_quotation using this code:

```text
# Assign quotation to content
content=Watson_quotation
```
Finally, for your question, use this text:

```type
"how many connections in the brain"
```


In [17]:
# Insert your code for Exercise 3 here

Watson_quotation = (
"The brain is the last and grandest biological frontier,"
"the most complex thing we have yet discovered in our universe."
"It contains hundreds of billions of cells interlinked through "
"trillions of connections. The brain boggles the mind."
)

# Define the context and the question you want answered
context = Watson_quotation

# Define the question
question = "how many connections in the brain"

# Run the QA model
result = qa_pipe(question=question, context=context)

# Pretty‑print the answer
print(f"Question: {question}")
print(f"Answer  : {result['answer']}")
print(f"Score   : {result['score']:.4f}")
print(f"Start   : {result['start']}  End: {result['end']}")

Question: how many connections in the brain
Answer  : trillions
Score   : 0.5811
Start   : 179  End: 188


If the code is correct you should see the following output:

```text
Question: how many connections in the brain
Answer  : trillions
Score   : 0.5811
Start   : 179  End: 188
```


------------------------

### **What does the `score` field mean in Hugging Face QA pipelines?**

When a question‑answering model returns a span, it also returns a
`score`.  The score is **not a hard probability** of correctness, but
the model’s internal confidence that the chosen start‑and‑end tokens
are the right answer.

#### **How it is computed**
1. The model outputs *start* and *end* logits for every token in the
   context.  
2. A softmax is applied to each set of logits → probabilities that sum
   to 1.  
3. The pipeline picks the span \([s, e]\) that maximises  
   \( P_{\text{start}}(s) \times P_{\text{end}}(e) \).  
   This product is the `score`.

#### **Interpreting a score**
| Score range | Rough meaning | What to do |
|-------------|---------------|------------|
| < 0.3 | Very low confidence | Treat the answer as unreliable; re‑phrase the question or add more context. |
| ≈ 0.5 | Moderate confidence | The answer is plausible but not guaranteed; double‑check if accuracy matters. |
| > 0.8 | High confidence | The answer is likely correct; you can use it as is. |

> **Caveat** – Hugging Face models are *not* calibrated to produce true
> probabilities.  Use the score to **rank or filter** results, not as an
> absolute correctness metric.

-------------------------------


## **NLP Language Translation**

**Language Translation** is a fascinating and practical application of natural language processing (NLP). It involves converting text from one language into another while preserving the original meaning, context, and nuances.

Hugging Face provides powerful pre-trained models for language translation. Here is a list of the popular models:

#### **List of Translators Used by Hugging Face**

Hugging Face offers a variety of translation models for different language pairs. Here are some popular ones:

1. **MarianMT Models**: These models support translation between multiple language pairs. For example:
   - `Helsinki-NLP/opus-mt-en-de`: English to German
   - `Helsinki-NLP/opus-mt-en-fr`: English to French
   - `Helsinki-NLP/opus-mt-en-es`: English to Spanish

2. **T5 Models**: These models can be fine-tuned for translation tasks. For example:
   - `t5-small`: A smaller version of the T5 model that can be fine-tuned for translation.
   - `t5-large`: A larger version of the T5 model with more parameters for better performance.

3. **mBART Models**: These models are designed for multilingual translation tasks. For example:
   - `facebook/mbart-large-50-many-to-many-mmt`: A multilingual model that supports translation between 50 languages.

4. **M2M100 Models**: These models are designed for many-to-many translation tasks. For example:
   - `facebook/m2m100_418M`: A model that supports translation between 100 languages.

You can find more translation models and explore their capabilities on the [Hugging Face Models page](https://huggingface.co/models?search=translate).


### Install `sacremoses` package

Before we can start translating, we need to install the `sacremoses` package.
The `sacremoses` package is a Python port of the `Moses tokenizer`, `truecaser`, and `normalizer`. It provides tools for text preprocessing, which are essential for various natural language processing (NLP) tasks. Here are some key features of sacremoses:

**Tokenizer:** The Moses tokenizer splits text into tokens (words, punctuation, etc.) while handling special characters and preserving the original meaning. For example, it can tokenize sentences with unusual symbols and punctuation.

**Detokenizer:** The Moses detokenizer reverses the tokenization process, converting tokens back into a coherent sentence.

**Truecaser:** The Moses truecaser adjusts the casing of words in a text to match typical usage patterns. It can be trained on a large corpus to learn the correct casing for words.

Google Colab doesn't normally include the `sacremoses` package but you can add it by running the following code cell.

In [18]:
# Install sacremoses package

!pip install sacremoses

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 19.6 MB/s eta 0:00:00


If the code is correct you should see the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image08G.png)

### Example 4 - Step 1: Select Translator

In this example we will use the `"Helsinki-NLP/opus-mt-en-de"` model. The **`Helsinki-NLP/opus-mt-en-de`** model is a powerful tool for translating text from English to German. Developed by the Language Technology Research Group at the University of Helsinki, this model is part of the `OPUS-MT` project, which provides open translation services for various language pairs

In [19]:
# Example 4 - Step 1: Setup translator

# Select translator
translator = pipeline("translation_en_to_de",
                      model="Helsinki-NLP/opus-mt-en-de")


config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/298M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/298M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/768k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/797k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

If the code is correct you should see the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image09G.png)

### Example 4 - Step 2: Translate Text

The following code translates Watson's quotation (`Watson_quotation`) that was used in **Exercise 3** into German.


In [20]:
# Example 4 - Step 2 Translate text

import textwrap
from transformers import pipeline

# Normalize the text by removing extra spaces
normalized_text = ' '.join(Watson_quotation.split())

# Print the normalized text with proper wrapping
wrapped_text = textwrap.fill(normalized_text, width=50)
print(wrapped_text)

# Print spacer
print("\n")

# Perform translation
outputs = translator(Watson_quotation, clean_up_tokenization_spaces=True, min_length=100)

# Get the translated text
translated_text = outputs[0]['translation_text']

# Remove excessive dots (e.g., ellipses)
cleaned_text = translated_text.rstrip('.')

# Break the cleaned text into separate lines
wrapped_text = textwrap.fill(cleaned_text, width=50)

print(wrapped_text)


The brain is the last and grandest biological
frontier,the most complex thing we have yet
discovered in our universe.It contains hundreds of
billions of cells interlinked through trillions of
connections. The brain boggles the mind.


Das Gehirn ist die letzte und großartigste
biologische Grenze, die komplexeste Sache, die wir
noch in unserem Universum entdeckt haben.Es
enthält Hunderte von Milliarden Zellen, die durch
Billionen von Verbindungen miteinander verbunden
sind.Das Gehirn verdreht den Geist.Das Gehirn ist
in der Lage, das Gehirn zu verschmelzen, und das
Gehirn ist in der Lage, das Gehirn zu
verschmelzen, indem es seine Zellen und Zellen
miteinander verschränkt, indem es seine Zellen
ineinander verschränkt


If the code is correct you should see the following output:

```text
The brain is the last and grandest biological
frontier,the most complex thing we have yet
discovered in our universe.It contains hundreds of
billions of cells interlinked through trillions of
connections. The brain boggles the mind.


Das Gehirn ist die letzte und großartigste
biologische Grenze, die komplexeste Sache, die wir
noch in unserem Universum entdeckt haben.Es
enthält Hunderte von Milliarden Zellen, die durch
Billionen von Verbindungen miteinander verbunden
sind.Das Gehirn verdreht den Geist.Das Gehirn ist
in der Lage, das Gehirn zu verschmelzen, und das
Gehirn ist in der Lage, das Gehirn zu
verschmelzen, indem es seine Zellen und Zellen
miteinander verschränkt, indem es seine Zellen
ineinander verschränkt
```
#### **Applications of Text Translation in Biomedical Contexts**

The ability to translate text into different languages offers significant value in biomedical research, healthcare, and public health. Here are some key applications:

##### 1. **Global Research Collaboration**
- Enables researchers worldwide to access scientific literature published in different languages
- Facilitates collaboration between international research teams
- Helps disseminate findings from non-English speaking research institutions

##### 2. **Clinical Documentation**
- Translates patient records for healthcare providers treating international patients
- Supports medical tourism where patients seek treatment in foreign countries
- Assists in transferring medical histories across borders

##### 3. **Public Health Communication**
- Translates health advisories and guidelines during disease outbreaks (e.g., COVID-19)
- Makes vaccination information accessible to diverse populations
- Helps communicate drug safety warnings globally

##### 4. **Drug Development & Regulatory Compliance**
- Translates clinical trial documentation for multinational studies
- Supports regulatory submissions to agencies in different countries (FDA, EMA, PMDA)
- Enables analysis of adverse event reports from global pharmacovigilance databases

##### 5. **Patient Care & Accessibility**
- Provides translated discharge instructions and medication guides
- Improves informed consent processes for non-native speakers
- Supports telemedicine consultations across language barriers

##### 6. **Literature Mining & Meta-Analysis**
- Allows inclusion of non-English studies in systematic reviews
- Reduces language bias in meta-analyses
- Expands the evidence base for clinical guidelines

---

#### ⚠️ **Important Caveat**

Note that in your output above, the German translation shows **repetition and degradation** toward the end:

> *"Das Gehirn ist in der Lage, das Gehirn zu verschmelzen..."* (repeated phrases)

This is a common issue with neural machine translation when using the `min_length` parameter, which forces the model to generate more text than the content warrants. For biomedical applications, **accuracy is critical**, so:

- Avoid forcing minimum lengths that exceed the natural translation length
- Always have translations reviewed by qualified human translators for clinical use
- Consider using specialized biomedical translation models for technical content



**NOTE:** If you get an error message it might be a consequence of Example 4 using your code from **Exercise 3** above.

## **NLP Summarization**

**Summarization** is a key NLP task that involves condensing a longer text into a shorter version while preserving the main ideas and important details. There are two primary types of summarization:

1. **Extractive Summarization:** This method involves selecting and extracting key sentences or phrases from the original text. The selected sentences are then combined to form a summary. It's like creating a highlight reel of the text.

2. **Abstractive Summarization:** This method involves generating new sentences that capture the essence of the original text. It requires the model to understand the context and rephrase the content in a concise manner. This approach is more challenging but can produce more natural and coherent summaries.

Summarization is an NLP task that summarizes a more lengthy text into just a few sentences.

#### **Use Cases**

**NLP summarization**—both extractive and the more recent abstractive methods powered by transformer architectures such as BERT, T5, and GPT—automatically condenses long documents into concise, coherent overviews while preserving key information. In computational biology, this capability is indispensable for navigating the deluge of biomedical literature and data reports. Researchers employ summarization to generate rapid literature reviews, extract essential findings from high‑throughput genomics, proteomics, and metabolomics papers, and produce concise summaries of experimental protocols or clinical trial outcomes. Additionally, summarization helps distill complex pathway and interaction network descriptions, create short reports of multi‑omics integration results, and aid in hypothesis generation by highlighting novel associations across datasets. By reducing manual curation effort, summarization accelerates discovery pipelines, improves reproducibility, and supports evidence‑based decision‑making in genomics, drug discovery, and personalized medicine.

### Setup the Text Summarizer

Run the code in the next cell to setup the summarizer pipeline.

In [21]:
# Setup summarizer pipeline

summarizer = pipeline("summarization")

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.22G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image10G.png)

### Example 5 - Step 1: Input Text

The code in the cell below creates a variable called `eg_text3` that contains the text to be summarized. This text is a discussion of the **CRISPER-Cas9 gene editing technology**.

In [22]:
# Example 5 - Step 1: Input Text


# Input the text to be summarized
eg_text3 = """
CRISPR-Cas9 gene editing technology represents one of the most significant
breakthroughs in molecular biology since the discovery of the DNA double helix.
This revolutionary tool allows scientists to make precise modifications to the
genetic code of virtually any organism, opening unprecedented possibilities
for treating genetic diseases, developing new therapies, and advancing our
understanding of fundamental biological processes. The technology has transformed
biomedical research and holds immense promise for clinical applications.

The CRISPR system was originally discovered as a natural defense mechanism in
bacteria, where it functions to protect against viral infections by recognizing
and destroying foreign genetic material. Scientists Jennifer Doudna and Emmanuelle
Charpentier recognized the potential of this system for targeted genome editing
and developed it into a versatile laboratory tool, work for which they were
awarded the Nobel Prize in Chemistry in 2020. The system consists of two key
components: a guide RNA that directs the machinery to the specific DNA sequence
of interest, and the Cas9 protein that acts as molecular scissors to cut the
DNA at the targeted location.

The implications for treating genetic diseases are profound. Conditions caused
by single-gene mutations, such as sickle cell disease, cystic fibrosis, and
Huntington's disease, are prime candidates for CRISPR-based therapies. In
December 2023, the first CRISPR-based treatment received regulatory approval
for sickle cell disease and beta-thalassemia, marking a historic milestone in
medicine. This therapy works by editing patients' own blood stem cells to
produce fetal hemoglobin, which compensates for the defective adult hemoglobin
responsible for the disease.

Cancer treatment represents another promising application of CRISPR technology.
Researchers are using gene editing to enhance CAR-T cell therapy, in which
patients' immune cells are modified to recognize and attack cancer cells.
CRISPR allows scientists to make multiple genetic modifications simultaneously,
improving the persistence and effectiveness of these therapeutic cells while
reducing the risk of adverse reactions. Clinical trials are underway for
various blood cancers and solid tumors.

Beyond direct therapeutic applications, CRISPR has become an indispensable
research tool for understanding disease mechanisms. Scientists can create
precise disease models by introducing specific mutations into cells or
laboratory animals, allowing them to study how genetic changes lead to
pathology. High-throughput CRISPR screens enable researchers to systematically
knock out genes across the entire genome to identify those essential for
particular biological processes or drug responses.

The technology continues to evolve rapidly. Base editing and prime editing
represent next-generation approaches that can make precise single-letter
changes to DNA without creating double-strand breaks, potentially reducing
off-target effects and expanding the range of treatable mutations. Researchers
are also developing CRISPR systems that target RNA rather than DNA, offering
temporary modifications that might be preferable for certain applications.

Ethical considerations surrounding CRISPR technology remain subjects of intense
debate. The 2018 announcement that a researcher had created gene-edited human
embryos that were brought to term sparked international condemnation and renewed
calls for strict oversight of germline editing. While somatic cell editing
affects only the individual patient, modifications to eggs, sperm, or embryos
would be inherited by future generations, raising profound questions about
consent, equity, and unintended consequences. Scientific organizations worldwide
have called for moratoriums on clinical germline editing until safety and
ethical frameworks can be established.

Delivery of CRISPR components to target tissues remains a significant technical
challenge, particularly for in vivo applications. Viral vectors, lipid
nanoparticles, and other delivery systems each have advantages and limitations
in terms of efficiency, tissue specificity, and immunogenicity. Overcoming
these barriers is essential for expanding CRISPR therapies beyond blood
disorders to conditions affecting the brain, heart, and other organs.
"""


If the code is correct, you should _not_ see any output.

### Example 5 - Step 2: Print Summary

The following code uses the pipeline created above to summarize `eg_text3` and print out the summary.

In [23]:
# Example 5 - Step 2: Print output

import textwrap
from transformers import pipeline

# Send text to summarizer
outputs = summarizer(eg_text3, max_length=500, min_length=200,
                     clean_up_tokenization_spaces=True)

# Get the summary text
summary_text = outputs[0]['summary_text']

# Break the summary into separate lines
wrapped_summary = textwrap.fill(summary_text, width=80)

# Print the wrapped summary
print(wrapped_summary)


 CRISPR-Cas9 gene editing technology represents one of the most significant
breakthroughs in molecular biology since the discovery of the DNA double helix.
The technology has transformed biomedical research and holds immense promise for
clinical applications. The implications for treating genetic diseases are
profound. Conditions caused by single-gene mutations, such as sickle cell
disease, cystic fibrosis, and Huntington's disease, are prime candidates for
CRISpr-based therapies. Clinical trials are underway for certain blood cancers
and solid tumors. CRIS PR technology continues to evolve rapidly. It is also an
indispensable research tool for understanding disease mechanisms. It has been
used to create disease models by introducing specific mutations into cells or
laboratory animals, allowing them to study how genetic changes lead to
pathology. It remains a significant technical technical challenge. Overcoming
these barriers is essential for expanding CRISplasticity and immunogenicit

If the code is correct, you should see something _similar_ to the following output:

```text
 CRISPR-Cas9 gene editing technology represents one of the most significant
breakthroughs in molecular biology since the discovery of the DNA double helix.
The technology has transformed biomedical research and holds immense promise for
clinical applications. The implications for treating genetic diseases are
profound. Conditions caused by single-gene mutations, such as sickle cell
disease, cystic fibrosis, and Huntington's disease, are prime candidates for
CRisPR-based therapies. CRISpr has become an indispensable research tool for
understanding disease mechanisms. The technology continues to evolve rapidly. It
continues to be an indispensable research tool to understand disease mechanisms,
especially for in vivo applications. It is also an indispensable tool for
scientists to create disease models by introducing specific mutations into cells
or animals, allowing them to study how genetic changes lead to pathology. It
remains a critical question about the safety and ethical considerations
surrounding CRispr technology. The 2018 announcement that a researcher had
created gene-edited human
```

#### **The Value of Text Summarization for Biomedical Professionals**

Text summarization using Natural Language Processing (NLP) offers significant benefits for researchers, clinicians, and other professionals working in biomedical fields. Here are the key advantages:

##### 1. **Managing Information Overload**
- Over 1 million new articles are added to PubMed annually
- Biomedical professionals cannot read every relevant publication in full
- Automated summarization condenses lengthy papers into digestible key points
- Enables researchers to quickly assess whether a full article warrants detailed reading

##### 2. **Accelerating Literature Reviews**
- Systematic reviews require screening thousands of abstracts and papers
- Summarization tools can extract core findings from multiple studies rapidly
- Reduces the time needed to identify relevant research for meta-analyses
- Helps maintain comprehensive coverage without sacrificing efficiency

##### 3. **Clinical Decision Support**
- Physicians need quick access to current evidence at the point of care
- Summarized clinical guidelines and research findings support faster decision-making
- Reduces cognitive load during time-sensitive patient encounters
- Helps translate lengthy clinical trial results into actionable insights

##### 4. **Drug Discovery & Development**
- Pharmaceutical researchers must review vast patent and scientific literature
- Summarization assists in competitive intelligence and prior art searches
- Condenses regulatory documents and clinical trial reports
- Speeds up identification of potential drug targets and safety signals

##### 5. **Grant Writing & Reporting**
- Researchers can quickly synthesize background literature for proposals
- Simplifies creation of progress reports and executive summaries
- Helps distill complex findings for non-specialist audiences and funding agencies

##### 6. **Medical Education**
- Students can grasp essential concepts from dense textbook chapters
- Summarized case studies facilitate efficient learning
- Supports continuing medical education by condensing new developments

---

##### ⚠️ **Important Considerations**

While summarization is powerful, biomedical professionals should be aware of limitations:

| Concern | Recommendation |
|---------|----------------|
| Loss of nuance | Verify critical details in the original source |
| Potential inaccuracies | Human review remains essential for clinical applications |
| Context dependency | Medical terminology may be misinterpreted by general models |
| Bias in training data | Use domain-specific biomedical models when possible |

---

##### **Conclusion**

Text summarization represents a valuable tool for managing the ever-growing volume of biomedical literature. When used appropriately alongside human expertise, it can enhance productivity, support evidence-based practice, and accelerate scientific discovery.


### **Exercise 5 - step 1: Input Text**

In the cell below, write the code to input `ex_text3`. Use this code snippet  that contains a discussion of the **Human Microbiome**:

```python
eg_text3 = """
The human microbiome represents one of the most fascinating and rapidly evolving
areas of biomedical research in the twenty-first century. This complex ecosystem
of trillions of microorganisms, including bacteria, viruses, fungi, and other
microscopic life forms, resides throughout the human body, with the greatest
concentration found in the gastrointestinal tract. These microbial communities
are not merely passive inhabitants; they play crucial roles in human health,
disease prevention, and even mental well-being.

Research has demonstrated that the gut microbiome influences numerous physiological
processes, including digestion, metabolism, immune system development, and
protection against pathogenic organisms. The bacteria in our intestines help
break down complex carbohydrates, synthesize essential vitamins such as vitamin K
and certain B vitamins, and produce short-chain fatty acids that provide energy
to colon cells. This symbiotic relationship between humans and their microbial
partners has evolved over millions of years, resulting in a finely tuned system
that benefits both host and microbe.

The connection between the gut microbiome and the immune system is particularly
noteworthy. Approximately seventy percent of the body's immune cells reside in
the gut-associated lymphoid tissue, where they constantly interact with and
respond to the microbial environment. This interaction helps train the immune
system to distinguish between harmful pathogens and beneficial or neutral
organisms. Disruptions to the microbiome, known as dysbiosis, have been linked
to various autoimmune conditions, including inflammatory bowel disease,
rheumatoid arthritis, and type 1 diabetes.

Perhaps most intriguing is the emerging understanding of the gut-brain axis,
a bidirectional communication network linking the gastrointestinal tract and
the central nervous system. The microbiome produces neurotransmitters such as
serotonin, dopamine, and gamma-aminobutyric acid, which can influence mood,
cognition, and behavior. Studies have shown correlations between specific
microbial profiles and conditions such as depression, anxiety, and autism
spectrum disorder, opening new avenues for therapeutic intervention.

The therapeutic potential of microbiome manipulation has generated considerable
interest in the medical community. Fecal microbiota transplantation has proven
remarkably effective in treating recurrent Clostridioides difficile infections,
with success rates exceeding ninety percent. Researchers are now investigating
whether similar approaches might benefit patients with inflammatory bowel disease,
metabolic syndrome, and neurological disorders. Additionally, the development of
targeted probiotics and prebiotics offers promise for more precise microbiome
modulation.

Advances in sequencing technology have revolutionized our ability to study the
microbiome. High-throughput sequencing methods allow researchers to identify
and quantify the thousands of microbial species present in a single sample,
while metagenomic approaches provide insights into the functional capabilities
of these communities. Machine learning algorithms are increasingly being applied
to microbiome data to identify disease biomarkers and predict treatment responses.

Despite remarkable progress, significant challenges remain in microbiome research.
The complexity and variability of microbial communities across individuals makes
it difficult to define a healthy microbiome. Factors such as diet, geography,
age, medications, and genetics all influence microbial composition, complicating
efforts to establish causal relationships between specific microbes and health
outcomes. Standardization of sample collection, processing, and analysis methods
is essential for ensuring reproducibility across studies.
"""

```

In [24]:
# Insert your code for Exercise 5 - Step 1 here

ex_text3 = """
The human microbiome represents one of the most fascinating and rapidly evolving
areas of biomedical research in the twenty-first century. This complex ecosystem
of trillions of microorganisms, including bacteria, viruses, fungi, and other
microscopic life forms, resides throughout the human body, with the greatest
concentration found in the gastrointestinal tract. These microbial communities
are not merely passive inhabitants; they play crucial roles in human health,
disease prevention, and even mental well-being.

Research has demonstrated that the gut microbiome influences numerous physiological
processes, including digestion, metabolism, immune system development, and
protection against pathogenic organisms. The bacteria in our intestines help
break down complex carbohydrates, synthesize essential vitamins such as vitamin K
and certain B vitamins, and produce short-chain fatty acids that provide energy
to colon cells. This symbiotic relationship between humans and their microbial
partners has evolved over millions of years, resulting in a finely tuned system
that benefits both host and microbe.

The connection between the gut microbiome and the immune system is particularly
noteworthy. Approximately seventy percent of the body's immune cells reside in
the gut-associated lymphoid tissue, where they constantly interact with and
respond to the microbial environment. This interaction helps train the immune
system to distinguish between harmful pathogens and beneficial or neutral
organisms. Disruptions to the microbiome, known as dysbiosis, have been linked
to various autoimmune conditions, including inflammatory bowel disease,
rheumatoid arthritis, and type 1 diabetes.

Perhaps most intriguing is the emerging understanding of the gut-brain axis,
a bidirectional communication network linking the gastrointestinal tract and
the central nervous system. The microbiome produces neurotransmitters such as
serotonin, dopamine, and gamma-aminobutyric acid, which can influence mood,
cognition, and behavior. Studies have shown correlations between specific
microbial profiles and conditions such as depression, anxiety, and autism
spectrum disorder, opening new avenues for therapeutic intervention.

The therapeutic potential of microbiome manipulation has generated considerable
interest in the medical community. Fecal microbiota transplantation has proven
remarkably effective in treating recurrent Clostridioides difficile infections,
with success rates exceeding ninety percent. Researchers are now investigating
whether similar approaches might benefit patients with inflammatory bowel disease,
metabolic syndrome, and neurological disorders. Additionally, the development of
targeted probiotics and prebiotics offers promise for more precise microbiome
modulation.

Advances in sequencing technology have revolutionized our ability to study the
microbiome. High-throughput sequencing methods allow researchers to identify
and quantify the thousands of microbial species present in a single sample,
while metagenomic approaches provide insights into the functional capabilities
of these communities. Machine learning algorithms are increasingly being applied
to microbiome data to identify disease biomarkers and predict treatment responses.

Despite remarkable progress, significant challenges remain in microbiome research.
The complexity and variability of microbial communities across individuals makes
it difficult to define a healthy microbiome. Factors such as diet, geography,
age, medications, and genetics all influence microbial composition, complicating
efforts to establish causal relationships between specific microbes and health
outcomes. Standardization of sample collection, processing, and analysis methods
is essential for ensuring reproducibility across studies.
"""

If the code is correct, you should _not_ see any output.

### **Exercise 5 - Step 2: Print Summary**

In the cell below, write the code to summarize the text in `ex_text3`and then print out this summary.

In [25]:
# Insert your code for Exercise 5 - Step 2 here

import textwrap
from transformers import pipeline

# Print spacer
print("\nSummary: \n")

# Send text to summarizer
outputs = summarizer(ex_text3, max_length=500, min_length=200,
                     clean_up_tokenization_spaces=True)

# Get the summary text
summary_text = outputs[0]['summary_text']

# Break the summary into separate lines
wrapped_summary = textwrap.fill(summary_text, width=80)

# Print the wrapped summary
print(wrapped_summary)



Summary: 

 The human microbiome represents one of the most fascinating and rapidly
evolving biomedical research in the twenty-first century. Microbiome is a
complex ecosystem of trillions of microorganisms, including bacteria, viruses,
fungi, and othermicroscopic life forms. These microbial communities play crucial
roles in human health, disease prevention, and mental well-being. Disruptions to
the gut microbiome, known as dysbiosis, have been linked to autoimmune
conditions, including inflammatory bowel disease, autoimmune arthritis, and type
1 diabetes. Fecal microbiota transplantation has proven to be effective in
treating recurrent Clostridioides difficile infections, with success rates
exceeding ninety percent. Machine learning algorithms are increasingly being
applied to microbiome data to identify disease biomarkers and predict treatment
responses to the treatment responses and to identify treatment responses. The
development of probiotics and prebiotics offers promise for mor

If the code is correct, you should see somethiog _similar_ to the following output:
```text
Summary:

 The human microbiome represents one of the most fascinating and rapidly
evolving areas of biomedical research in the twenty-first century. Microbiome is
a complex ecosystem of trillions of microorganisms, including bacteria, viruses,
fungi, and other microorganisms. Microbes play crucial roles in human health,
disease prevention, and even mental well-being. Disruptions to the microbiome,
known as dysbiosis, have been linked  to autoimmune conditions, including
inflammatory bowel disease,  heumatoid arthritis, and type 1 diabetes. Fecal
microbiota transplantation has proven reporably effective in treating recurrent
Clostridioides difficile infections, with success rates exceeding ninety
percent. The microbiome produces neurotransmitters such as serotonin, dopamine,
and gamma-aminobutyric acid, which can influence mood, behavior, and behavior.
Machine learning algorithms are increasingly being applied to microbiome data to
identify disease biomarkers and predict treatment responses. The development of
probiotics and prebiotics offers promise
```

## **NLP Text Generation**

**Text generation** is a fundamental and powerful capability in natural language processing (NLP), and Hugging Face provides several models that excel in this area. Here's why text generation is important and how it is utilized:

1. **Creative Writing:** Text generation models can help authors, poets, and scriptwriters generate new content, brainstorm ideas, or even complete unfinished pieces. This can significantly boost creativity and productivity.

2. **Conversational Agents:** Text generation models are used to create chatbots and virtual assistants that can engage in natural and meaningful conversations with users. These models can provide customer support, answer queries, and even offer companionship.

3. **Content Creation:** Businesses and content creators use text generation to produce articles, social media posts, product descriptions, and more. This helps in maintaining a consistent flow of content and saves time.

4. **Language Translation:** Text generation plays a crucial role in machine translation, where models generate translated text from one language to another, ensuring that the meaning and nuances are preserved.

5. **Summarization:** As mentioned earlier, text generation models can summarize lengthy documents into concise summaries, making it easier to digest large volumes of information quickly.

6. **Code Generation:** Developers use text generation models to assist in coding by generating code snippets, documenting code, or even completing functions based on prompts.

7. **Educational Tools:** Text generation can be used to create educational content, generate quizzes, provide explanations, and even tutor students in various subjects.

Hugging Face offers several powerful models for text generation, such as GPT-3, BERT, T5, and more. These models leverage large-scale pre-training on diverse datasets to understand and generate human-like text.

### Setup Generator Pipeline

Run the code in the cell below to set up a pipeline to generate text.

In [26]:
# Setup Generator Pipeline

from transformers import pipeline
import torch

def setup_pipeline():
    try:
        # Check if CUDA is available
        if torch.cuda.is_available():
            device = 0  # Use first GPU
            print(f"GPU detected: {torch.cuda.get_device_name(0)}")
            print(f"Number of GPUs available: {torch.cuda.device_count()}")
            print("Using GPU for text generation")
        else:
            device = -1
            print("No GPU found. Using CPU for text generation")

        # Setup pipeline
        generator = pipeline("text-generation",
                           model="openai-community/gpt2",
                           device=device)

        return generator

    except Exception as e:
        print(f"Error initializing pipeline: {e}")
        print("Falling back to CPU")
        return pipeline("text-generation",
                       model="openai-community/gpt2",
                       device=-1)

# Initialize the pipeline
generator = setup_pipeline()


GPU detected: Tesla T4
Number of GPUs available: 1
Using GPU for text generation


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image11G.png)

### Example 6: Generate New Text

The code in the cell below generates additional text after the end of Shakespear's `Sonnet 18`.


In [27]:
# Example 6 - Step 2: Generate New Text

from transformers import pipeline
import torch
from urllib.request import urlopen

# Check if CUDA is available
device = 0 if torch.cuda.is_available() else -1

# Setup pipeline with explicit model specification
eg_generator = pipeline("text-generation",
                     model="openai-community/gpt2",
                     device=device)

# Read sample text, a poem
URL = "https://biologicslab.co/BIO1173/data/sonnet_18.txt"
f = urlopen(URL)
eg_text = f.read().decode("utf-8")

# Print original text
print("\nOriginal Text:---------------------- \n")
print(eg_text)
print("\nGenerated Text:------------------- \n")

# Fix the warnings by using max_new_tokens instead of max_length
# Also add truncation and other parameters to avoid warnings
outputs = eg_generator(eg_text,
                    max_new_tokens=200,  # Use this instead of max_length
                    num_return_sequences=1,
                    truncation=True,  # Explicitly enable truncation
                    do_sample=True,   # Enable sampling for better generation
                    temperature=0.7,  # Control randomness (0.0 to 1.0)
                    top_k=50,         # Top-k sampling
                    top_p=0.95)       # Nucleus sampling

eg_generated_text = outputs[0]['generated_text']
print(eg_generated_text)


model.safetensors:   0%|          | 0.00/1.22G [00:00<?, ?B/s]


Original Text:---------------------- 

Shall I compare thee to a summer's day?
Thou art more lovely and more temperate:
Rough winds do shake the darling buds of May,
And summer's lease hath all too short a date:
Sometime too hot the eye of heaven shines,
And often is his gold complexion dimm'd;
And every fair from fair sometimes declines,
By chance or nature's changing course untrimm'd;
But thy eternal summer shall not fade
Nor lose possession of that fair thou owest;
Nor shall Death brag thou wander'st in his shade,
When in eternal lines to time thou growest.

Generated Text:------------------- 

Shall I compare thee to a summer's day?
Thou art more lovely and more temperate:
Rough winds do shake the darling buds of May,
And summer's lease hath all too short a date:
Sometime too hot the eye of heaven shines,
And often is his gold complexion dimm'd;
And every fair from fair sometimes declines,
By chance or nature's changing course untrimm'd;
But thy eternal summer shall not fade
Nor l

If the code is correct you should see something similar to this output.

```text

Original Text:----------------------

Shall I compare thee to a summer's day?
Thou art more lovely and more temperate:
Rough winds do shake the darling buds of May,
And summer's lease hath all too short a date:
Sometime too hot the eye of heaven shines,
And often is his gold complexion dimm'd;
And every fair from fair sometimes declines,
By chance or nature's changing course untrimm'd;
But thy eternal summer shall not fade
Nor lose possession of that fair thou owest;
Nor shall Death brag thou wander'st in his shade,
When in eternal lines to time thou growest.

Generated Text:-------------------

Shall I compare thee to a summer's day?
Thou art more lovely and more temperate:
Rough winds do shake the darling buds of May,
And summer's lease hath all too short a date:
Sometime too hot the eye of heaven shines,
And often is his gold complexion dimm'd;
And every fair from fair sometimes declines,
By chance or nature's changing course untrimm'd;
But thy eternal summer shall not fade
Nor lose possession of that fair thou owest;
Nor shall Death brag thou wander'st in his shade,
When in eternal lines to time thou growest.
And in eternal lines to time thou growest.
And in eternal lines to time thou grewest.
And in eternal lines to time thou grewest.
But thy eternal summer shall not fade.
                                          
```
NOTE: If your rerun the code several times, you will generate quite different outputs!

### **Comparison of Original vs. Generated Text**

The following is an analysis of the Original Text (Sonnet 18) and the Generated Text (shown above) by `OpenAI's` **`ChatGPT-4o`** model.

##### **1. Fidelity to Original**
- **Original Text**: Maintains Shakespeare’s iambic pentameter, rhyme scheme (ABAB CDCD EFEF GG), and thematic focus on eternal beauty and poetic immortality.
- **Generated Text**: The first 12 lines are identical to the original, but the continuation breaks from the sonnet structure and introduces new, loosely connected ideas.

##### **2. Coherence and Structure**
- **Original**: Cohesive and logically structured argument about the enduring nature of the subject’s beauty.
- **Generated**: Becomes repetitive and structurally disorganized. Phrases like “the boy shall be called, as he is now” are repeated without clear poetic or thematic purpose.

##### **3. Style and Language**
- **Original**: Rich in metaphor (“eye of heaven,” “eternal summer”), elevated diction, and poetic devices.
- **Generated**: Attempts poetic language but lacks the sophistication and precision of Shakespeare. The metaphors are simpler and less evocative (“sun and moon are the sweetest kisses of love”).

##### **4. Thematic Depth**
- **Original**: Explores themes of beauty, mortality, and the power of poetry to preserve.
- **Generated**: Shifts toward themes of identity and romantic roles but without clear development or philosophical insight.

#### **5. Creativity and Originality**
- **Generated Text**: Shows an attempt to emulate poetic style and extend the theme, but the repetition and lack of clarity suggest limitations in the model’s understanding of poetic form and nuance.

#### **Summary Table**

| Aspect              | Original Text                  | Generated Text                          |
|---------------------|--------------------------------|------------------------------------------|
| Structure           | Sonnet form, 14 lines          | Starts as sonnet, then diverges          |
| Language            | Elevated, metaphorical         | Poetic attempt, but repetitive           |
| Coherence           | Logical and thematic unity     | Fragmented and repetitive                |
| Creativity          | Masterful and timeless         | Imitative, with limited poetic insight   |

---

It should be noted that the newest Frontier LLM models from companies such as **Google**, **OpenAI** and **Anthropic** could probably do a considerably better job.


It seems like the text generation output continued far beyond the original Sonnet 18, incorporating additional and somewhat repetitive lines. This can happen with generative models when they attempt to create content based on a given prompt.

### **Exercise 6: Generate New Text**

In the cell below, write the code to generate additional text after the end of Shakespear's `Sonnet 66`.


In [28]:
# Example 6 - Step 2: Generate New Text

from transformers import pipeline
import torch
from urllib.request import urlopen

# Check if CUDA is available
device = 0 if torch.cuda.is_available() else -1

# Setup pipeline with explicit model specification
ex_generator = pipeline("text-generation",
                     model="openai-community/gpt2",
                     device=device)

# Read sample text, a poem
URL = "https://biologicslab.co/BIO1173/data/sonnet_66.txt"
f = urlopen(URL)
ex_text = f.read().decode("utf-8")

# Print original text
print("\nOriginal Text:---------------------- \n")
print(ex_text)
print("\nGenerated Text:------------------- \n")

# Fix the warnings by using max_new_tokens instead of max_length
# Also add truncation and other parameters to avoid warnings
outputs = ex_generator(ex_text,
                    max_new_tokens=200,  # Use this instead of max_length
                    num_return_sequences=1,
                    truncation=True,  # Explicitly enable truncation
                    do_sample=True,   # Enable sampling for better generation
                    temperature=0.7,  # Control randomness (0.0 to 1.0)
                    top_k=50,         # Top-k sampling
                    top_p=0.95)       # Nucleus sampling

ex_generated_text = outputs[0]['generated_text']
print(ex_generated_text)



Original Text:---------------------- 

Tired with all these, for restful death I cry:
As, to behold desert a beggar born,
And needy nothing trimmed in jollity,
And purest faith unhappily forsworn,
And gilded honor shamefully misplaced,
And maiden virtue rudely strumpeted,
And right perfection wrongfully disgraced,
And strength by limping sway disablèd,
And art made tongue-tied by authority,
And folly, doctor-like, controlling skill,
And simple truth miscalled simplicity,
And captive good attending captain ill.
 Tired with all these, from these would I be gone,
 Save that, to die, I leave my love alone.

Generated Text:------------------- 

Tired with all these, for restful death I cry:
As, to behold desert a beggar born,
And needy nothing trimmed in jollity,
And purest faith unhappily forsworn,
And gilded honor shamefully misplaced,
And maiden virtue rudely strumpeted,
And right perfection wrongfully disgraced,
And strength by limping sway disablèd,
And art made tongue-tied by authori

If the code is correct you should see something _similar_ to this output.

```text

Original Text:----------------------

Tired with all these, for restful death I cry:
As, to behold desert a beggar born,
And needy nothing trimmed in jollity,
And purest faith unhappily forsworn,
And gilded honor shamefully misplaced,
And maiden virtue rudely strumpeted,
And right perfection wrongfully disgraced,
And strength by limping sway disablèd,
And art made tongue-tied by authority,
And folly, doctor-like, controlling skill,
And simple truth miscalled simplicity,
And captive good attending captain ill.
 Tired with all these, from these would I be gone,
 Save that, to die, I leave my love alone.

Generated Text:-------------------

Tired with all these, for restful death I cry:
As, to behold desert a beggar born,
And needy nothing trimmed in jollity,
And purest faith unhappily forsworn,
And gilded honor shamefully misplaced,
And maiden virtue rudely strumpeted,
And right perfection wrongfully disgraced,
And strength by limping sway disablèd,
And art made tongue-tied by authority,
And folly, doctor-like, controlling skill,
And simple truth miscalled simplicity,
And captive good attending captain ill.
 Tired with all these, from these would I be gone,
 Save that, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these, to die, I leave my love alone.
And in these
```
NOTE: If your rerun the code several times, you will generate quite different outputs! Therefore it is highly unlikely that your Generated Text will be anything like this example.

## **Biomedical Named Entity Recognition (NER)**

An important use case for the Hugging Face NLP pipelines in biomedicine is **Named Entity Recognition (NER)** using a biomedical-specific model.


#### **Why This Example Works Well**

| Advantage | Description |
|-----------|-------------|
| **Highly Practical** | Extracting entities from text is a real-world task in clinical and research settings |
| **Visually Compelling** | Results clearly show identified drugs, diseases, genes, etc. |
| **Domain-Specific** | Uses a model trained specifically on biomedical literature |
| **Builds on Previous Examples** | Shows a different pipeline task beyond classification, translation, and summarization |



### Example 7 - Step 1: Create NER Pipeline

The code in the next cell generates a NER pipeline called `pubmed_pipeline` using the `d4data/biomedical-ner-all` model. The `d4data/biomedical-ner-all model` is a specialized Named Entity Recognition (NER) tool hosted on Hugging Face. It is designed to extract structured biomedical concepts (like diseases, symptoms, and medications) from unstructured text, such as PubMed abstracts or clinical notes.

This model acts as a **processing engine**. You would build a pipeline that fetches text from PubMed (the input) and feeds it into this model to automatically tag and extract specific medical terms (the output).

In [29]:
# Create NER Pipeline

from transformers import pipeline

pubmed_pipeline = pipeline(
    "ner",
    model="d4data/biomedical-ner-all",
    aggregation_strategy="simple"
)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/266M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/373 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image12G.png)

### Example 7 - Step 2: Perform Named Entity Recognition (NER)


Example 7 shows how to use a Hugging Face NLP pipeline to automatically identify and extract biomedical entities from clinical text.

##### **What the Code Does**

1. **Defines Input Text**: A sample clinical trial description is stored in `eg_biomedical_text`, containing information about a cancer treatment study including drug names, dosages, diseases, and adverse events.

2. **Extracts Entities**: The `pubmed_pipeline()` function (a pre-configured NER pipeline) processes the text and identifies biomedical entities such as:
   - Drug names (pembrolizumab, carboplatin, paclitaxel)
   - Diseases (non-small cell lung cancer, pneumonitis)
   - Dosages (200 mg)
   - Administration routes (intravenously)
   - Adverse events (fatigue, nausea)

3. **Displays Results**: The code loops through each identified entity and prints:
   - The extracted word/phrase
   - Its entity category (e.g., Drug, Disease, Dosage)
   - A confidence score indicating how certain the model is about the classification

##### **Why This Matters**

Named Entity Recognition transforms unstructured clinical text into structured, actionable data. This capability is essential for tasks such as mining medical literature, parsing electronic health records, and supporting pharmacovigilance activities.


In [30]:
# Example 7: Biomedical Named Entity Recognition (NER)

# Set Clean Word Distance
WORD_DISTANCE=25

# Input clinical trial description
eg_clinical_text = """
A phase III randomized controlled trial evaluated the efficacy of pembrolizumab
in combination with chemotherapy for patients with metastatic non-small cell
lung cancer. Patients received 200 mg of pembrolizumab intravenously every
three weeks along with carboplatin and paclitaxel. Results showed that the
combination therapy significantly improved progression-free survival compared
to chemotherapy alone. Common adverse events included fatigue, nausea, and
immune-related pneumonitis. The study was conducted at Memorial Sloan Kettering
Cancer Center and MD Anderson Cancer Center.
"""

# Extract biomedical entities
entities = pubmed_pipeline(eg_clinical_text)

# Display results
print("Extracted Disease Entities:\n")
for entity in entities:
    word = entity['word'].strip()
    # Skip punctuation, short words, and phrases that start with common non-disease words
    skip_starts = ['the ', 'a ', 'in ', 'and ', 'after ', 'for ', ', ', '. ', 'last ']
    if len(word) > 3 and not any(word.lower().startswith(s) for s in skip_starts):
        # Clean up apostrophe spacing (e.g., "Alzheimer ' s" → "Alzheimer's")
        clean_word = word.replace(" ' ", "'")
        print(f"{clean_word:<{WORD_DISTANCE}} → {entity['entity_group']:{WORD_DISTANCE}} (confidence: {entity['score']:.2f})")

Extracted Disease Entities:

phase iii                 → Detailed_description      (confidence: 0.96)
random                    → Diagnostic_procedure      (confidence: 0.94)
controlled trial          → Diagnostic_procedure      (confidence: 0.92)
##mb                      → Medication                (confidence: 0.73)
##rolizumab               → Medication                (confidence: 0.89)
chemotherapy              → Medication                (confidence: 1.00)
metastatic                → Detailed_description      (confidence: 0.77)
lung                      → Biological_structure      (confidence: 1.00)
200 mg                    → Dosage                    (confidence: 1.00)
##mb                      → Medication                (confidence: 0.76)
##rol                     → Medication                (confidence: 0.98)
##izumab                  → Medication                (confidence: 0.70)
intra                     → Administration            (confidence: 1.00)
##ven                 

If the code is correct, you should see something _similar_ to the following output:

```text
Extracted Disease Entities:

phase iii                 → Detailed_description      (confidence: 0.96)
random                    → Diagnostic_procedure      (confidence: 0.94)
controlled trial          → Diagnostic_procedure      (confidence: 0.92)
##mb                      → Medication                (confidence: 0.73)
##rolizumab               → Medication                (confidence: 0.89)
chemotherapy              → Medication                (confidence: 1.00)
metastatic                → Detailed_description      (confidence: 0.77)
lung                      → Biological_structure      (confidence: 1.00)
200 mg                    → Dosage                    (confidence: 1.00)
##mb                      → Medication                (confidence: 0.76)
##rol                     → Medication                (confidence: 0.98)
##izumab                  → Medication                (confidence: 0.70)
intra                     → Administration            (confidence: 1.00)
##ven                     → Administration            (confidence: 0.99)
##ously                   → Administration            (confidence: 0.91)
every three weeks         → Dosage                    (confidence: 0.98)
##bo                      → Medication                (confidence: 0.93)
##platin                  → Medication                (confidence: 0.97)
##lita                    → Medication                (confidence: 0.93)
therapy                   → Medication                (confidence: 0.69)
progression               → Diagnostic_procedure      (confidence: 0.36)
chemotherapy              → Medication                (confidence: 1.00)
immune                    → Detailed_description      (confidence: 0.99)
memorial sloan kettering cancer center → Nonbiological_location    (confidence: 1.00)
```
#### **Interpreting the NER Output**

##### **Understanding the Results**

The output shows biomedical entities extracted from the clinical trial text. Each line displays:
- **The extracted text** (word or phrase)
- **Entity category** (what type of biomedical concept it represents)
- **Confidence score** (0.00 to 1.00, where 1.00 = 100% confident)


##### **Entity Categories Explained**

| Category | Description | Examples from Output |
|----------|-------------|---------------------|
| **Medication** | Drugs and therapeutic agents | chemotherapy, carboplatin, paclitaxel |
| **Dosage** | Drug amounts and frequencies | 200 mg, every three weeks |
| **Administration** | How medication is given | intravenously |
| **Disease_disorder** | Medical conditions | pneumonitis (shown as "p") |
| **Biological_structure** | Body parts and organs | lung |
| **Diagnostic_procedure** | Tests and trial methods | controlled trial |
| **Detailed_description** | Qualifiers and descriptors | phase iii, metastatic, immune |
| **Nonbiological_location** | Institutions and places | Memorial Sloan Kettering Cancer Center |

##### **Understanding Tokenization Artifacts**

You'll notice fragmented words with `##` symbols (e.g., `pe`, `##mb`, `##rolizumab`). This is due to **subword tokenization**:

- The model breaks unknown or complex words into smaller pieces
- `##` indicates a continuation of the previous token
- **pembrolizumab** → `pe` + `##mb` + `##rolizumab`
- **carboplatin** → `car` + `##bo` + `##platin`
- **intravenously** → `intra` + `##ven` + `##ously`

This is normal behavior for transformer models but can make output harder to read.

##### **Confidence Score Interpretation**

| Score Range | Interpretation |
|-------------|----------------|
| **0.90 - 1.00** | High confidence – reliable classification |
| **0.70 - 0.89** | Moderate confidence – likely correct |
| **Below 0.70** | Lower confidence – may need verification |

Examples from output:
- ✅ `chemotherapy → Medication (1.00)` – Very reliable
- ✅ `200 mg → Dosage (1.00)` – Very reliable
- ⚠️ `therapy → Medication (0.69)` – Less certain
- ⚠️ `progression → Diagnostic_procedure (0.36)` – Low confidence


### **Exercise 7 - Step 1: Create NER Pipeline**

In the next cell below, write the code to generate a NER pipeline called `disease_pipeline` that uses the `alvaroalon2/biobert_diseases_ner` model.

In [31]:
# Insert your code for Exercise 7 - Step 1 here

from transformers import pipeline

# Step 1: Create a disease-focused NER pipeline
# Replace the model with: alvaroalon2/biobert_diseases_ner
disease_pipeline = pipeline(
    "ner",
    model="alvaroalon2/biobert_diseases_ner",  # Fill in the model name
    aggregation_strategy="simple"
)

config.json:   0%|          | 0.00/746 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/431M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/431M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

If the code is correct you should see something similar to the following output:

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image13G.png)

### **Exercise 7 - Step 2: Perform Named Entity Recognition (NER)**

Use this code for your clinical description

```python
# Input clinical description
ex_clinical_text = """
The patient presented with a complex medical history including type 2 diabetes
mellitus, hypertension, and chronic kidney disease. Previous diagnoses included
rheumatoid arthritis and major depressive disorder. Family history was significant
for Alzheimer's disease in the mother and coronary artery disease in the father.
The patient was recently evaluated for suspected Parkinson's disease after
experiencing tremors and bradykinesia. Additionally, the patient has a history
of asthma and was treated for pneumonia last winter. Laboratory results raised
concerns for possible hepatitis C infection, pending confirmatory testing.

"""
```
**CODE HINTS:**
1. Make sure to use your `disease_pipeline` when you extract entities from the `ex_clinical_text`.


In [32]:
# Insert your code for Exercise 7 - Step 2 here

# Set Clean Word Distance
WORD_DISTANCE=25

# Input clinical description
ex_clinical_text = """
The patient presented with a complex medical history including type 2 diabetes
mellitus, hypertension, and chronic kidney disease. Previous diagnoses included
rheumatoid arthritis and major depressive disorder. Family history was significant
for Alzheimer's disease in the mother and coronary artery disease in the father.
The patient was recently evaluated for suspected Parkinson's disease after
experiencing tremors and bradykinesia. Additionally, the patient has a history
of asthma and was treated for pneumonia last winter. Laboratory results raised
concerns for possible hepatitis C infection, pending confirmatory testing.

"""

# Extract biomedical entities
entities = disease_pipeline(ex_clinical_text)

# Display results
print("Extracted Disease Entities:\n")
for entity in entities:
    word = entity['word'].strip()
    # Skip punctuation, short words, and phrases that start with common non-disease words
    skip_starts = ['the ', 'a ', 'in ', 'and ', 'after ', 'for ', ', ', '. ', 'last ']
    if len(word) > 3 and not any(word.lower().startswith(s) for s in skip_starts):
        # Clean up apostrophe spacing (e.g., "Alzheimer ' s" → "Alzheimer's")
        clean_word = word.replace(" ' ", "'")
        print(f"{clean_word:<{WORD_DISTANCE}} → {entity['entity_group']:{WORD_DISTANCE}} (confidence: {entity['score']:.2f})")


Extracted Disease Entities:

type 2 diabetes mellitus  → DISEASE                   (confidence: 1.00)
hypertension              → DISEASE                   (confidence: 0.98)
chronic kidney disease    → DISEASE                   (confidence: 1.00)
rheumatoid arthritis      → DISEASE                   (confidence: 1.00)
depressive disorder       → DISEASE                   (confidence: 1.00)
Alzheimer's disease       → DISEASE                   (confidence: 1.00)
coronary artery disease   → DISEASE                   (confidence: 0.99)
Parkinson's disease       → DISEASE                   (confidence: 1.00)
tremors                   → DISEASE                   (confidence: 1.00)
bradykinesia              → DISEASE                   (confidence: 1.00)
asthma                    → DISEASE                   (confidence: 0.97)
pneumonia                 → DISEASE                   (confidence: 1.00)
hepatitis C infection     → DISEASE                   (confidence: 1.00)


If the code is correct, you should see something _similar_ to the following output:

```text

Extracted Disease Entities:

type 2 diabetes mellitus  → DISEASE                   (confidence: 1.00)
hypertension              → DISEASE                   (confidence: 0.98)
chronic kidney disease    → DISEASE                   (confidence: 1.00)
rheumatoid arthritis      → DISEASE                   (confidence: 1.00)
depressive disorder       → DISEASE                   (confidence: 1.00)
Alzheimer's disease       → DISEASE                   (confidence: 1.00)
coronary artery disease   → DISEASE                   (confidence: 0.99)
Parkinson's disease       → DISEASE                   (confidence: 1.00)
tremors                   → DISEASE                   (confidence: 1.00)
bradykinesia              → DISEASE                   (confidence: 1.00)
asthma                    → DISEASE                   (confidence: 0.97)
pneumonia                 → DISEASE                   (confidence: 1.00)
hepatitis C infection     → DISEASE                   (confidence: 1.00)
```
#### **Summary of Disease Recognition Results**

###### **Overview**

The BioBERT disease NER model successfully processed the clinical text and identified multiple disease entities. However, the output reveals an important issue with the model's entity boundary detection.

##### **Diseases Successfully Identified**

The model correctly recognized the following diseases in the patient with high confidence:

| Disease | Confidence |
|---------|------------|
| Type 2 diabetes mellitus | 1.00 |
| Hypertension | 0.98 |
| Chronic kidney disease | 1.00 |
| Rheumatoid arthritis | 1.00 |
| Depressive disorder | 1.00 |
| Alzheimer's disease | 1.00 |
| Coronary artery disease | 0.99 |
| Parkinson's disease | 1.00 |
| Tremors | 1.00 |
| Bradykinesia | 1.00 |
| Asthma | 0.97 |
| Pneumonia | 1.00 |
| Hepatitis C infection | 1.00 |

##### **Conclusion**

The model **successfully identified all major diseases** in the clinical text.


# **Lesson Turn-In**

When you have completed and run all of the code cells, use the `File --> Print.. --> Microsoft Print to PDF` to generate your PDF if you are running `MS Windows`. If you have a Mac, use the `File --> Print.. --> Save as PDF`

In either case, save your PDF as Copy of Class_05_1.lastname.pdf where lastname is your last name, and upload the file to Canvas.

## **Lizard Tail**

## **Apple Mac Studio with M3 Ultra**

![___](https://biologicslab.co/BIO1173/images/class_05/Mac_Studio.jpg)

The Mac Studio is a small-form-factor workstation computer developed and marketed by Apple Inc. It is one of four desktop computers in the Mac lineup, sitting above the consumer-range Mac Mini and iMac, and positioned below the Mac Pro. It is configurable with either the M4 Max or M3 Ultra system on a chip.

## On-Line Purchase

If you are looking for a new computer to do a little homework, surf the web or run Large Language Models locally, you can't go wrong buying the **Apple Mac Studio with M3 Ultra**

![___](https://biologicslab.co/BIO1173/images/class_05/class_05_1_image21A.png)

### **Why the Mac Studio Ultra with M3 Is Useful for Running LLMs Locally**

#### 🔧 Key Hardware Advantages

##### 1. M3 Ultra Chip Architecture
- Combines two M3 Max chips, offering **up to 32 CPU cores and 80 GPU cores**.
- Unified memory architecture with **up to 192GB of RAM**, crucial for loading large models entirely into memory.

##### 2. High Memory Bandwidth
- Apple Silicon chips have **extremely fast memory bandwidth**, aiding rapid data movement during inference and training.

##### 3. Neural Engine
- The **Apple Neural Engine (ANE)** can accelerate certain ML tasks.
- While not fully utilized by all ML frameworks yet, it's promising for future optimization.

##### 4. Energy Efficiency
- Much more **power-efficient** than traditional workstations with discrete GPUs.
- Ideal for long-running tasks without excessive heat or power draw.

---

#### 🧠 Software Ecosystem for LLMs on macOS

##### 1. Support for ML Frameworks
- macOS supports **PyTorch**, **TensorFlow**, and **Hugging Face Transformers**.
- Tools like **Llama.cpp**, **GGUF**, and **MLX (Apple’s ML framework)** are optimized for Apple Silicon.

#####2. Running Quantized Models
- Models like **LLaMA 2**, **Mistral**, or **Phi-3** can run in 4-bit or 8-bit quantized formats.
- With 192GB RAM, even **larger models** like LLaMA 3 70B can be experimented with in quantized form.

##### 3. MLX Framework
- Apple’s MLX framework is designed to take full advantage of Apple Silicon.
- Makes it easier to run and experiment with models locally.

---

#### 🧪 Use Cases for Local LLMs

- **Privacy-sensitive applications** (e.g., medical or educational data).
- **Offline access** for fieldwork or remote teaching.
- **Rapid prototyping** without relying on cloud APIs.
- **Fine-tuning small models** for domain-specific tasks.

---

Would you like help setting up a local LLM on a Mac Studio Ultra, or exploring which models would run best on it?


## Overview
### Rear ports

The Mac Studio is a desktop personal computer, designed to sit between the consumer-level Mac Mini and the professional-targeted Mac Pro. The Mac Studio has an identical width and depth to the contemporary Mac mini, 7.7 inches (200 mm), but it stands taller at 3.7 inches (94 mm).

The Mac Studio was initially offered in two ARM-based SoC: the M1 Max or the M1 Ultra, which combines two M1 Max chips in one package. It has:

- Four Thunderbolt 4 (USB 4) ports
- Two USB 3.0 Type-A ports
- HDMI (up to 4K @ 60 Hz)
- 10Gb Ethernet with Lights Out Management
- Headphone jack

The front panel has:

- Two USB-C ports (Thunderbolt 4 in M1 Ultra models)
- SD card slot (supports SDXC cards and UHS-II bus)

It is cooled by a pair of double-sided blowers and a mesh of holes on the bottom and back of the case, which helps reduce fan noise. Nevertheless, there have been reports of excessive fan noise.

Mac Studio models with the Ultra SoC are heavier than the Max-equipped models, as they exchange the aluminum heat sink for one composed of copper. Apple says the Mac Studio performs 50% faster than a Mac Pro with a 16-core Intel Xeon processor.

The Mac Studio was introduced alongside the Apple Studio Display, a 27-inch 5K monitor with:

- Integrated 12 MP camera
- Six-speaker sound system with spatial audio and Dolby Atmos support
- Height adjustable stand

Customers reported months-long shipping delays for the Mac Studio, attributed to a global chip shortage.

## Updates
- **June 5, 2023 (WWDC)**: Updated Mac Studio models with M2 Max and M2 Ultra chips.
  - Bluetooth 5.3
  - Wi-Fi 6E
  - Support for up to six 6K monitors
  - 8K display support over Thunderbolt and HDMI

- **March 5, 2025**: Updated Mac Studio models with M4 Max and M3 Ultra chips (shipping began March 12).
  - Thunderbolt 5
  - Memory configurable up to 512 GB
  - Storage configurable up to 16 TB (M3 Ultra)
  - M3 Ultra included due to no existing Ultra chips in the M4 line

## Repairability

![Mac Studio with Studio Display, Magic Keyboard, and Magic Trackpad in an Apple Store](image-placeholder removable flash storage ports, with one or two in use depending on storage configuration. While swapping flash storage cards between same-size models is possible with Apple Configurator restore, upgrading is not officially supported.

Criticism includes:

- Limited upgradeability unfriendly to right to repair
- SSD controller integrated into SoC for encryption
- SSD placement beneath exposed power supply

## Reception

> This section needs expansion. You can help by adding to it. (March 2025)

## Specifications
| Model | 2022 | 2023 | 2025 |
|-------|------|------|------|
| **Announced** | Mar 8, 2022 | Jun 5, 2023 | Mar 5, 2025 |
| **Released** | Mar 18, 2022 | Jun 13, 2023 | Mar 12, 2025 |
| **Discontinued** | Jun 5, 2023 | Mar 5, 2025 | In production |

### Chip Configurations

- **2022**
  - M1 Max: 10-core CPU, 24-core GPU, 16-core Neural Engine
  - M1 Ultra: 20-core CPU, 48-core GPU, 32-core Neural Engine

- **2023**
  - M2 Max: 12-core CPU, 30-core GPU, 16-core Neural Engine
  - M2 Ultra: 24-core CPU, 60-core GPU, 32-core Neural Engine

- **2025**
  - M4 Max: 14-core CPU, 32-core GPU, 16-core Neural Engine
  - M3 Ultra: 28-core CPU, 60-core GPU, 32-core Neural Engine

### Memory

- 2022: 32 GB (up to 64 GB)
- 2023: 64 GB (up to 128 GB)
- 2025:
  - M4 Max: 36 GB (up to 128 GB)
  - M3 Ultra: 96 GB (up to 512 GB)

### Storage

- 2022 & 2023: 512 GB (Max) or 1 TB (Ultra), up to 8 TB
- 2025: Up to 16 TB (Ultra)

### Wireless

- 2022: Wi-Fi 6, Bluetooth 5.0
- 2023: Wi-Fi 6E, Bluetooth 5.3

### Connectivity

- Thunderbolt 4/5 USB-C ports
- USB-A ports
- HDMI 2.0/2.1
- 10Gb Ethernet
- 3.5 mm headphone jack
- SDXC card slot
### Power

- 2022: 370 W
- 2023: 480 W

### Dimensions
- 3.7 in × 7.7 in × 7.7 in

### Weight

- Max: ~5.9 lb
- Ultra: ~7.9–8.0 lb

### Emissions

- Varies by model and configuration (e.g., 262–382 kg CO₂e)

## Software and Operating Systems

All Mac Studio models ship with macOS, starting with **macOS Monterey**.

### Supported macOS Releases

| OS Release | 2022 | 2023 | 2025 |
|------------|------|------|------|
| 12 Monterey | 12.2 | — | — |
| 13 Ventura | Yes | 13.4 | — |
| 14 Sonoma | Yes | Yes | — |
| 15 Sequoia | Yes | Yes | 15.2 |
| 26 Tahoe | Yes | Yes | Yes |

---

**See also**: [List of Mac models]
